OtoSoft.Plant.WebUI/Areas/Admin/Models/Herb/HerbCreateVM.cs
using Microsoft.AspNetCore.Mvc.Rendering;

namespace OtoSoft.Plant.WebUI.Areas.Admin.Models.Herb
{
    public class HerbCreateVM
    {
        public string Name { get; set; }
        public string Description { get; set; }
        public IFormFile Image { get; set; }
        public List<string> Complaints { get; set; }
    }
}

OtoSoft.Plant.WebUI/Areas/Admin/Models/Herb/HerbUpdateVM.cs
namespace OtoSoft.Plant.WebUI.Areas.Admin.Models.Herb
{
    public class HerbUpdateVM
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public IFormFile Image { get; set; }
        public List<string> Complaints { get; set; }
    }
}

OtoSoft.Plant.WebUI/Areas/Admin/Controllers/HerbController.cs
using Core.Utilities.ImageTools;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using OtoSoft.Plant.Business.Abstract;
using OtoSoft.Plant.Entities.DTOs.Complaint;
using OtoSoft.Plant.Entities.DTOs.ComplaintHerb;
using OtoSoft.Plant.Entities.DTOs.Herb;
using OtoSoft.Plant.WebUI.Areas.Admin.Models.Herb;
using System.Text.Json;

namespace OtoSoft.Plant.WebUI.Areas.Admin.Controllers
{
    [Area("Admin")]
    
    public class HerbController : Controller
    {
        private readonly IHerbService _herbService;
        private readonly IComplaintService _complaintService;


        public HerbController(IHerbService herbService, IComplaintService complaintService)
        {
            _herbService = herbService;
            _complaintService = complaintService;
        }

        [HttpGet]
        public IActionResult Index()
        {
            List<HerbDto> herbDtos = _herbService.GetWithComplaints();
            return View(herbDtos);
        }

        [HttpGet]

        public IActionResult Detail(int id)
        {
            HerbDto herbDto = _herbService.GetById(id);
            return View(herbDto);
        }

        [HttpGet]

        public IActionResult Edit(int id)
        {
            HerbDto herbDto = _herbService.GetById(id);
            return View(herbDto);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(HerbUpdateVM herbUpdateVM)
        {
            HerbUpdateDto herbUpdateDto = new HerbUpdateDto
            {
                Id = herbUpdateVM.Id,
                Description = herbUpdateVM.Description,
                Name = herbUpdateVM.Name,
                Image = ImageConverterTool.ConvertToBase64(herbUpdateVM.Image).Result,

            };
            foreach (var item in herbUpdateVM.Complaints)
            {
                herbUpdateDto.Complaints.Add(new ComplaintHerbCreateDto
                {
                    ComplaintId = Convert.ToInt32(item)
                });
            }
            _herbService.Update(herbUpdateDto);
            return View();
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            _herbService.Delete(id);
            
            return Ok(Json(_herbService.GetAll()));
        }

        [HttpGet]
        public IActionResult Add()
        {
            ViewBag.ComplaintDto = _complaintService.GetAll().Select(x => new SelectListItem { Text = x.Name, Value = x.Id.ToString() }).ToList();
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Add(HerbCreateVM herbCreateVM)
        {

            HerbCreateDto herbCreateDto = new HerbCreateDto();
            herbCreateDto.Image = ImageConverterTool.ConvertToBase64(herbCreateVM.Image).Result;
            herbCreateDto.Name = herbCreateVM.Name;
            herbCreateDto.Description = herbCreateVM.Description;
            foreach (var item in herbCreateVM.Complaints)
            {
                herbCreateDto.Complaints.Add(new ComplaintHerbCreateDto
                {
                    ComplaintId = Convert.ToInt32(item)
                });
            }

            _herbService.Add(herbCreateDto);
            ViewBag.ComplaintDto = _complaintService.GetAll().Select(x => new SelectListItem { Text = x.Name, Value = x.Id.ToString() }).ToList();
            return View();
        }
    }
}

OtoSoft.Plant.WebUI/Controllers/ComplaintController.cs
using Microsoft.AspNetCore.Mvc;
using OtoSoft.Plant.Business.Abstract;
using OtoSoft.Plant.Entities.DTOs.Complaint;

namespace OtoSoft.Plant.WebUI.Controllers
{
   
    public class ComplaintController : Controller
    {
        private readonly IComplaintService _complaintService;

        public ComplaintController(IComplaintService complaintService)
        {
            _complaintService = complaintService;
        }

        [HttpGet]
        public IActionResult Index()
        {
            List<ComplaintDto> complaintDtos = _complaintService.GetAll();
            return View(complaintDtos);
        }

        [HttpGet]
        public IActionResult Detail(int id)
        {
            ComplaintDto complaintDto = _complaintService.GetById(id);
            return View(complaintDto);
        }
    }
}

OtoSoft.Plant.WebUI/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using OtoSoft.Plant.Business.Abstract;
using OtoSoft.Plant.Entities.DTOs.Herb;

namespace OtoSoft.Plant.WebUI.Controllers
{     
    public class HomeController : Controller
    {
        private readonly IHerbService _herbService;

        public HomeController(IHerbService herbService)
        {
            _herbService = herbService;
        }
        [HttpGet]
        public IActionResult Index()
        {
            List<HerbDto> herbDtos= _herbService.GetWithComplaints();
            return View(herbDtos);
        }
        [HttpGet]
        public IActionResult Detail(int id)
        {
            HerbDto herbDto = _herbService.GetById(id);
            return View(herbDto);
        }


    }
}

OtoSoft.Plant.WebUI/Areas/Admin/Views/Herb/Add.cshtml
@using OtoSoft.Plant.Entities.DTOs.Complaint
@model OtoSoft.Plant.Entities.DTOs.Herb.HerbCreateDto


@{
    ViewData["Title"] = "Add";
    Layout = "~/Views/Shared/_Layout.cshtml";
    List<SelectListItem> complaintDtos = ViewBag.ComplaintDto as List<SelectListItem>;
}

<h1>Add</h1>

<h4>HerbCreateDto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Add" asp-antiforgery="true" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label"></label>
                <input type="file" asp-for="Image" class="form-control" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Complaints" class="control-label"></label>
                <select asp-for="Complaints" name="Complaints" asp-items="@complaintDtos" multiple>
                    <option value="">Please choose complaints</option>
                </select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

OtoSoft.Plant.WebUI/Areas/Admin/Views/Herb/Detail.cshtml
@model OtoSoft.Plant.Entities.DTOs.Herb.HerbDto

@{
    ViewData["Title"] = "Detail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Detail</h1>

<div>
    <h4>HerbDto</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Image)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

OtoSoft.Plant.WebUI/Areas/Admin/Views/Herb/Edit.cshtml
@model OtoSoft.Plant.Entities.DTOs.Herb.HerbDto

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>HerbDto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" asp-antiforgery="true" method="post" asp-area="Admin" asp-controller="Herb" enctype="multipart/form-data">
           @Html.AntiForgeryToken();
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label for="Image" class="control-label"></label>
                <input type="file" name="Image" class="form-control" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

OtoSoft.Plant.WebUI/Areas/Admin/Views/Herb/Index.cshtml
@using OtoSoft.Plant.Entities.DTOs.Herb
@model List<HerbDto>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">


    <div class="col-12 text-end">
        <a asp-action="Add" class="btn btn-success">
            Create Herb
        </a>


    </div>

    <div class="col-12">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>Herb Id</th>
                    <th>Herb Name</th>
                    <th>Herb Description</th>
                    <th>Herb Image</th>
                    <th>Herb Complaints</th>
                    <th>Process</th>
                </tr>
            </thead>
            <tbody id="tableData">
                @foreach (var herb in Model)
                {
                    <tr>
                        <td>@herb.Id</td>
                        <td>@herb.Name</td>
                        <td>@herb.Description</td>
                        <td><image src="@herb.Image" style="width:50px; height:50px;"></image></td>
                        <td>
                            @foreach (var item in herb.ComplaintDto)
                            {
                                <a href="/Complaint/Detail/@item.Id">@item.Name</a>
                            }
                        </td>
                        <td>
                            <a href="/Admin/Herb/Edit/@herb.Id">Edit</a>
                            <button class="btn btn-danger" id="deleteBtn" onclick="deleteHerb(@herb.Id)">Sil</button>

                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

<script src="~/jquery/jquery.min.js"></script>
<script src="~/jquery-ajax-unobtrusive/jquery.unobtrusive-ajax.min.js"></script>
<script>


    function deleteHerb(id) {
        $.ajax({
            type: "GET",
            url: "/Admin/Herb/Delete/" + id,
            contentType: "application/json",
            success: function(data) {
                console.log(data)
                $.each(data.value, function(index, value) {
                    $("#tableData").append(`
                        <tr>
                            <td>${value.Id}</td>
                            <td>${value.Name}</td>
                            <td>${value.Description}</td>
                            <td><image src="${value.Image}" style="width:50px; height:50px;"></image></td>
                            <td>
                            <a href="/Admin/Herb/Edit/${value.Id}">Edit</a>
                            <button class="btn btn-danger" id="deleteBtn" onclick="deleteHerb(${value.Id})">Sil</button>

                             </td>
                        </tr>
                    `)

                })
                
                
            },
            error: function() {
                alert("as")
            }
        })

    }
</script>

OtoSoft.Plant.WebUI/Views/Complaint/Detail.cshtml
@model OtoSoft.Plant.Entities.DTOs.Complaint.ComplaintDto

@{
    ViewData["Title"] = "Detail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Detail</h1>

<div>
    <h4>ComplaintDto</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
</div>
<div>
    
    <a asp-action="Index">Back to List</a>
</div>

OtoSoft.Plant.WebUI/Views/Complaint/Index.cshtml
@model IEnumerable<OtoSoft.Plant.Entities.DTOs.Complaint.ComplaintDto>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                
                <a asp-action="Detail" asp-route-id="@item.Id">Detail</a>
                
            </td>
        </tr>
}
    </tbody>
</table>

OtoSoft.Plant.WebUI/Views/Home/Detail.cshtml
@model OtoSoft.Plant.Entities.DTOs.Herb.HerbDto

@{
    ViewData["Title"] = "Detail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Detail</h1>

<div>
    <h4>HerbDto</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd class = "col-sm-10">
            <image src="@Model.Image" style="width:100px;height:100px;"></image>
        </dd>
    </dl>
</div>
<div>
    
    <a asp-action="Index">Back to List</a>
</div>

OtoSoft.Plant.WebUI/Views/Home/Index.cshtml
@model IEnumerable<OtoSoft.Plant.Entities.DTOs.Herb.HerbDto>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Image)
            </th>
            <th>
                Complaints
            </th>
            <th>

            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    <img src="@item.Image" width="100" height="100" />
                </td>
                <td>

                    @foreach (var complaint in item.ComplaintDto)
                    {
                        <a asp-controller="Complaint" asp-action="Detail"  asp-route-id="@complaint.Id">@complaint.Name</a>
                    }

                </td>
                <td>
                    <a asp-action="Detail" asp-route-id="@item.Id">Detail</a>
                </td>
                
            </tr>
        }
    </tbody>
</table>

OtoSoft.Plant.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/twitter-bootstrap/css/bootstrap.min.css" rel="stylesheet" />

</head>
<body>

    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" href="#">OtoSoft</a>
            
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Home" asp-action="Index">Herbs</a>
                    </li>
                     <li class="nav-item">
                        <a class="nav-link" asp-controller="Complaint" asp-action="Index">Complaints </a>
                    </li>
                </ul>
            </div>
            
        </nav>
    </header>
    <main class="container">
        <section>
            @RenderBody()
        </section>
    </main>
</body>
</html>